#!/bin/bash
# Rebuilds /var/lib/bc-data/warehouse.duckdb from the current snapshot and the
# permanent archive.
#
# Builds into a temp file and swaps atomically, for the same reason the snapshot
# does: DuckDB allows one writer per file, so rebuilding in place would collide
# with any read-only query the app is running. Swapping means a reader either
# gets the whole old warehouse or the whole new one.
#
# Exit codes: 0 ok, 1 missing input, 2 build failed, 3 verification failed.

set -uo pipefail

# cron's PATH is /usr/bin:/bin and does not include /usr/local/bin, where duckdb
# is installed. Without this the build fails under cron and only under cron.
export PATH="/usr/local/bin:/usr/bin:/bin"

BASE="/var/lib/bc-data"
SQL="$(dirname "$0")/../sql/build-warehouse.sql"
DEST="$BASE/warehouse.duckdb"
TMP="$BASE/.warehouse.duckdb.tmp"

log() { echo "$(date -u '+%Y-%m-%d %H:%M:%S') $*"; }

command -v duckdb > /dev/null      || { log "FATAL: duckdb not on PATH"; exit 1; }
[ -f "$BASE/snapshots/fleet.db" ] || { log "FATAL: no snapshot"; exit 1; }
[ -f "$SQL" ]                     || { log "FATAL: no $SQL"; exit 1; }

rm -f "$TMP" "$TMP.wal"
log "Building warehouse ..."
START=$(date +%s)

if ! duckdb "$TMP" < "$SQL" > /dev/null; then
  log "FATAL: build failed, keeping the previous warehouse"
  rm -f "$TMP" "$TMP.wal"
  exit 2
fi

# Guide identity: resolve every spelling of a person's name to one member_id.
# Computed in Node because it needs accent stripping, aliases and Levenshtein.
# It exits non-zero if any guide resolves to nobody, and that MUST fail the
# build: an unresolved guide means someone's hours silently vanish from a
# report, which is precisely the class of quiet wrong answer this project is
# built to prevent. The script targets the temp warehouse via BC_WAREHOUSE.
if ! BC_WAREHOUSE="$TMP" node "$(dirname "$0")/resolve-guides.js"; then
  log "FATAL: guide name resolution failed, keeping the previous warehouse"
  rm -f "$TMP" "$TMP.wal"
  exit 2
fi

if ! duckdb "$TMP" < "$(dirname "$0")/../sql/resolve-guides-post.sql" > /dev/null; then
  log "FATAL: attaching guide identity failed, keeping the previous warehouse"
  rm -f "$TMP" "$TMP.wal"
  exit 2
fi

# Confirmed uploads. The warehouse is dropped and rebuilt every hour, so every
# uploaded table has to be recreated from its Parquet or it vanishes at :35.
# The file is generated by src/ingest.js whenever an upload is confirmed.
UPLOADS_SQL="$(dirname "$0")/../sql/build-uploads.sql"
if [ -f "$UPLOADS_SQL" ] && ! duckdb "$TMP" < "$UPLOADS_SQL" > /dev/null; then
  log "FATAL: rebuilding uploaded tables failed, keeping the previous warehouse"
  rm -f "$TMP" "$TMP.wal"
  exit 2
fi

# Verify before publishing. An empty or half-built warehouse must never replace
# a working one: every number the tool reports would silently change.
CHECK=$(duckdb "$TMP" -noheader -list -c "
  SELECT (SELECT COUNT(*) FROM bc.departures) || '|' ||
         (SELECT COUNT(*) FROM bc.bookings)   || '|' ||
         (SELECT COUNT(*) FROM bc.products);" 2>/dev/null)
DEPS=$(echo "$CHECK" | cut -d'|' -f1)
BOOKS=$(echo "$CHECK" | cut -d'|' -f2)
PRODS=$(echo "$CHECK" | cut -d'|' -f3)

if [ "${DEPS:-0}" -lt 100 ] || [ "${BOOKS:-0}" -lt 100 ] || [ "${PRODS:-0}" -lt 12 ]; then
  log "FATAL: verification failed (departures=$DEPS bookings=$BOOKS products=$PRODS). Keeping previous."
  rm -f "$TMP" "$TMP.wal"
  exit 3
fi

mv -f "$TMP" "$DEST"
rm -f "$TMP.wal" "$DEST.wal"

ELAPSED=$(( $(date +%s) - START ))
SIZE=$(du -h "$DEST" | cut -f1)
log "OK: $DEPS departures, $BOOKS bookings, ${SIZE}, ${ELAPSED}s -> $DEST"
