-- GENERATED by src/ingest.js. Do not edit by hand.
--
-- Recreates every confirmed upload in the warehouse from its Parquet copy.
-- build-warehouse.sql drops and rebuilds the warehouse hourly, so without this
-- an uploaded table would vanish within the hour of being confirmed.

CREATE SCHEMA IF NOT EXISTS bc;

CREATE OR REPLACE TABLE bc."fh_sales_history" AS SELECT * FROM read_parquet('/var/lib/bc-data/raw/fh_sales_history/up_07d81dc615f7c69d07.parquet');
